let
    Source = Customers_Extract_Filter,
    // Change Type **See _Data_Documentation Workbook for details on type
    #"Changed Type" = Table.TransformColumnTypes(Source,
    {{"Deleted (*)", type text}, {"Division", type text}, {"Customer#", type text}, {"Allow New POS Documents (Y/N)", type text}, {"Use Instead Customer#", type text}, {"Use Instead Name", type text}, {"Sales Ranking Combined Customer#", type text}, {"Sales Ranking Combined Name", type text}, {"Sales Ranking Exclude (Y/N)", type text}, {"Customer Name", type text}, {"Customer Name (Extended)", type text}, {"Street Address", type text}, {"Street Address (Extended)", type text}, {"City  -  State/Province", type text}, {"Postal Code", type text}, {"Customer Tracked as Contact (Y/N)", type text}, {"Customer First Name (Contacts)", type text}, {"Customer Initial (Contacts)", type text}, {"Customer Last Name (Contacts)", type text}, {"Customer Company Name (Contacts)", type text}, {"Territory Code (Contacts)", type text}, {"Address - Line 1 (Contacts)", type text}, {"Address - Line 2 (Contacts)", type text}, {"Address - Line 3 (Contacts)", type text}, {"Address - City (Contacts)", type text}, {"Address - State/Prov (Contacts)", type text}, {"Customer Email (Contacts)", type text}, {"Customer Website (Contacts)", type text}, {"Day Area Code", type text}, {"Day Prefix", type text}, {"Day Number", type text}, {"Work Area Code", type text}, {"Work Prefix", type text}, {"Work Number", type text}, {"Work Extension", type text}, {"Fax Area Code", type text}, {"Fax Prefix", type text}, {"Fax Number", type text}, {"A/P Persons Phone#", type text}, {"A/P Persons Fax#", type text}, {"A/P Persons Name", type text}, {"A/P # with customer", type text}, {"Current # of Unpaid Invoices     (*NF*)", type text}, {"Balance    Total", type number}, {"Balance   Current", type number}, {"Balance  30 Day", type number}, {"Balance  60 Day", type number}, {"Balance  90 Day", type number}, {"Balance 120 Day", type number}, {"Balance Svc Chg", type number}, {"Balance at Peak", type number}, {"A/R GL Acct#", type text}, {"Date Added (CCYYMMDD)", type text}, {"Date Added", type date}, {"Date Added Days (Today - Added)", Int64.Type}, {"Open Item=O, Bal.Frwd=B", type text}, {"Credit Established (Y or N)", type text}, {"Credit Limit", type number}, {"Credit Code (1)", type text}, {"Credit Code (2)", type text}, {"Receivables Long Comment", type text}, {"Marketing Edit Code: 01 (W)", type text}, {"Marketing Edit Code: 02 (V)", type text}, {"Marketing Edit Code: 03 (E)", type text}, {"Marketing Edit Code: 04 (R)", type text}, {"Marketing Edit Code: 05 (M)", type text}, {"Marketing Edit Code: 06 (L)", type text}, {"Marketing Edit Code: 07 (C)", type text}, {"Marketing Edit Code: 08 (T)", type text}, {"Marketing Sort Code: 01", type text}, {"Marketing Sort Code: 02", type text}, {"Marketing Sort Code: 03", type text}, {"Marketing Sort Code: 04", type text}, {"Marketing Sort Code: 05", type text}, {"Marketing Sort Code: 06", type text}, {"Marketing Sort Code: 07", type text}, {"Marketing Sort Code: 08", type text}, {"Marketing Sort Code: 09", type text}, {"Marketing Sort Code: 10", type text}, {"Print Invoice (Y or N=Archive Only)", type text}, {"Print Statements (Y or N)", type text}, {"Email Invoices (Y or N)", type text}, {"Email Statements (Y or N)", type text}, {"Cash Only (Y/N)", type text}, {"Internal/Warranty (I/W)", type text}, {"Group Code", type text}, {"Discount Code", type text}, {"Quantity Discount (Y/N)", type text}, {"Tax Code (Standard: 1 character)", type text}, {"Tax Code (Advanced: 3 character)", type text}, {"Tax Type", type text}, {"Tax Number", type text}, {"GST Method (0/1/2/3)", type text}, {"GST Tax Number", type text}, {"SIC code", type text}, {"DUNS Number", type text}, {"DUNS Rating", type text}, {"FIPS code (State)", type text}, {"FIPS code (County)", type text}, {"Customer Rank", type text}, {"Freon Certification #", type text}, {"Rental Damage Waiver (Y/N)", type text}, {"Last Invoice Date (CCYYMMDD)", type text}, {"Last Invoice Date", type date}, {"Last Invoice Days (Today-Last Invoice)", Int64.Type}, {"Last Invoice Number", type text}, {"Last Invoice Amount", type number}, {"Last Payment Date (CCYYMMDD)", type text}, {"Last Payment Date", type date}, {"Last Payment Days (Today-Last Payment)", Int64.Type}, {"Last Payment Invoice #", type text}, {"Last Payment Amount", type number}, {"Annual Interest Rate", type number}, {"Basic Interest Charge", type number}, {"Charge Interest (Y/N)", type text}, {"Days till Interest", Int64.Type}, {"Days Collection Critical", Int64.Type}, {"Last Letter Date (CCYYMMDD)", type text}, {"Last Letter Date", type date}, {"Last Letter Days (Today-Lst Ltr)", Int64.Type}, {"Last Letter Number", type text}, {"Last Date Age Calc (CCYYMMDD)", type text}, {"Last Date Age Calculated", type date}, {"Last Date Age Calc Days(Today-Last Age)", Int64.Type}, {"Average # days Invoices Paid     (*NF*)", type number}, {"Roundup Interest Charge (Y/N)", type text}, {"Last Interest Date (CCYYMMDD)", type text}, {"Last Interest Date", type date}, {"Last Interest Days (Today-Last Interest)", Int64.Type}, {"Last Interest Invoice #", type text}, {"Last Interest Amount", type number}, {"Last Statement Date(CCYYMMDD)", type text}, {"Last Statement Date", type date}, {"Last Statement Days (Today-Last Stmnt)", Int64.Type}, {"Last Statement Balance", type number}}
    ),
    // Combine Name, City, State, Zip into column
    #"Inserted Customer Name-Location" = Table.AddColumn(#"Changed Type", "Customer Name-Location", each Text.Combine({[Customer Name], [#"City  -  State/Province"], [Postal Code]}, ", "), type text),
    // Combine day phone parts
    #"Inserted Phone Day" = Table.AddColumn(#"Inserted Customer Name-Location", "Phone Day", each Text.Combine({[Day Area Code], [Day Prefix], [Day Number]}, "-"), type text),
    // Combine work phone parts
    #"Inserted Phone Work" = Table.AddColumn(#"Inserted Phone Day", "Phone Work", each Text.Combine({[Work Area Code], [Work Prefix], [Work Number]}, "-"), type text)
in
    #"Inserted Phone Work"