let
    //Combine the statc history file and dynamic current file in to single data set to transform
    Source = POS_Detail_Extract_Filter,
    // Specify all column type, generated from data documentation workbook
    #"Change Type" = Table.TransformColumnTypes(#"Source",{
        {"Division", type text}, {"Address/Stock flag (A/S)", type text}, {"Address#/Stock#", type text}, {"Customer Name", type text}, {"Customer Contact Notes", type text}, {"Customer Tracked as Contact (Y/N)", type text}, {"Customer Contact Territory Code", type text}, {"Customer Contact Territory Description", type text}, {"Customer Contact Sales Rep Addrs#", type text}, {"Customer Contact Sales Rep First Name", type text}, {"Customer Contact Sales Rep Last Name", type text}, {"Stock# In Date (CCYYMMDD)", type text}, {"Stock# In Date", type text}, {"Stock# In Days (Today - In Date)", Int64.Type}, {"Document#", type text}, {"Document Code", type text}, {"Document Type (W/S/Q)", type text}, {"Document Status (O/R/C/k=Cancelled)", type text}, {"Document Posted? (P or ' ')", type text}, {"Date Opened (CCYYMMDD)", type text}, {"Date Opened", type date}, {"Days since Opened (Today-Opened)", Int64.Type}, {"Date Closed/Printed (CCYYMMDD)", type text}, {"Date Closed/Printed", type date}, {"Date Posted (CCYYMMDD)", type text}, {"Date Posted", type date}, {"Detail: Format for Sales code", type text}, {"Detail: Line Segmentation", type text}, {"Detail: Line Sales code", type text}, {"Detail: Line Sales code Description", type text}, {"Detail: Line Number", Int64.Type}, {"Detail: Int./Warr. (I/W if open,  i/w if closed)", type text}, {"Detail: Line Description", type text}, {"Detail: Line Tax code (Standard: 1 character)", type text}, {"Detail: Line Tax code (Advanced: 3 character)", type text}, {"Detail: Line Tax Type", type text}, {"Detail: Line GST Rate", type text}, {"Detail: Line Discount code", type text}, {"Detail: Line Discount Rate", type number}, {"Detail: Line Quantity", type number}, {"Detail: Line Price", type number}, {"Detail: Line Price[Ext] (Qty x Price)", type number}, {"Detail: Line Discount (Price[Ext] x Discount Rate)", type number}, {"Detail: Line Price[Dscnt] (Price[Ext] - Discount)", type number}, {"Detail: Line Cost", type number}, {"Detail: Line Cost[Ext] (Qty x Cost)", type number}, {"Detail: Line Price[Net] (Price[Dscnt] - Cost[Ext])", type number}, {"Detail: Part Profit Margin (100*Price[Net]/Price[Dscnt])", type number}, {"Detail: Part Vendor Code", type text}, {"Detail: Part Class Code", type text}, {"Detail: Part Number", type text}, {"Detail: Part Serial Number", type text}, {"Detail: Part Ext Warranty", type text}, {"Detail: Part Ext Warranty Memo", type text}, {"Detail: Part Priority Order Code", type text}, {"Detail: Part Price Code", type text}, {"Detail: Part Bin Location", type text}, {"Detail: Part Bin Location-2", type text}, {"Detail: Part Warr flag", type text}, {"Detail: Part Stocking Ind.", type text}, {"Detail: Part No Demand flag", type text}, {"Detail: Part Superseded flag", type text}, {"Detail: Part MFR - Market Code", type text}, {"Detail: Part MFR - Product Line", type text}, {"Detail: Part MFR - Product Code", type text}, {"Detail: Part MFR - Price Category", type text}, {"Detail: Part MFR - Promo ID", type text}, {"Detail: Labor Tech Number", type text}, {"Detail: Labor Date (CCYYMMDD)", type text}, {"Detail: Labor Date worked", type date}, {"Detail: Labor TimeOut(HHMMSS)", type text}, {"Detail: Labor Hrs Reported", type number}, {"Detail: Labor Hrs Billed", type number}, {"Detail: Labor Rate", type number}, {"Detail: Labor Billed[Ext] (Billed Hours x Billed Rate)", type number}, {"Detail: Labor Discount (Billed[Ext] x Discount Rate)", type number}, {"Detail: Labor Billed[Net] (Billed[Ext] - Discount)", type number}, {"Detail: Labor Job Code", type text}, {"Detail: Labor Job (ThemoKing)", type text}, {"Detail: Labor TimeClock Status Code", Int64.Type}, {"Detail: Labor TimeClock Work Type", Int64.Type}, {"Detail: Note Line", type text}, {"Detail: WG Unit Number", type text}, {"Detail: WG Unit Status (A/R/F/S)", type text}, {"Detail: WG Unit Make (Short)", type text}, {"Detail: WG Unit Make (Long)", type text}, {"Detail: WG Unit Model (Short)", type text}, {"Detail: WG Unit Model (Long)", type text}, {"Detail: WG Unit Description", type text}, {"Detail: WG Unit Serial Number", type text}, {"Detail: WG Unit In Date (CCYYMMDD)", type text}, {"Detail: WG Unit In Date", type date}, {"Detail: WG Unit In Days (Today - In Date)", Int64.Type}, {"Detail: WG Warr Exp(CCYYMMDD)", type text}, {"Detail: WG Warr Exp Date", type date}, {"Detail: WG Warr Code", type text}, {"Detail: Rental Unit#", type text}, {"Detail: Rental Unit Make (Short)", type text}, {"Detail: Rental Unit Make (Long)", type text}, {"Detail: Rental Unit Model (Short)", type text}, {"Detail: Rental Unit Model (Long)", type text}, {"Detail: Rental Unit Description", type text}, {"Detail: Rental Unit Serial#", type text}, {"Detail: Rental Status Flag (Rent=R / Unrent=U / Bypass=B)", type text}, {"Detail: Rental Rate Code (custom code only)", type text}, {"Detail: Rental Out(CCYYMMDD)", type text}, {"Detail: Rental Out Date", type date}, {"Detail: Rental In (CCYYMMDD)", type text}, {"Detail: Rental In Date", type date}, {"Detail: Rental Hr Meter Out", type number}, {"Detail: Rental Hr Meter In", type number}
        })
    // TODO Combine labor and parts totals? or do in DAX? 

in
    #"Change Type"