let
    //Combine the statc history file and dynamic current file in to single data set to transform
    Source = POS_Summary_Extract_Filter,
    // Specify all column type, generated from data documentation workbook
    Change_Type = Table.TransformColumnTypes(#"Source",{{"Division", type text}, {"Addrs/Stk flag (A/S)", type text}, {"Address#/Stock#", type text}, {"Customer Name", type text}, {"Customer Name (Extended)", type text}, {"Customer Street Address", type text}, {"Customer Street Address (Extended)", type text}, {"Customer City/State/Province", type text}, {"Customer Postal Code", type text}, {"Customer Phone-1 Area Code", type text}, {"Customer Phone-2 PreFix", type text}, {"Customer Phone-3 Base Number", type text}, {"Customer Default EMAIL address", type text}, {"Customer Default Tax Code (Standard: 1 character)", type text}, {"Customer Default Tax Code (Advanced: 3 character)", type text}, {"Customer Default Tax Type", type text}, {"Customer Default Tax Number", type text}, {"Customer Marketing Sort Code: 01", type text}, {"Customer Marketing Sort Code: 02", type text}, {"Customer Marketing Sort Code: 03", type text}, {"Customer Marketing Sort Code: 04", type text}, {"Customer Marketing Sort Code: 05", type text}, {"Customer Marketing Sort Code: 06", type text}, {"Customer Marketing Sort Code: 07", type text}, {"Customer Marketing Sort Code: 08", type text}, {"Customer Marketing Sort Code: 09", type text}, {"Customer Marketing Sort Code: 10", type text}, {"Stock# Status", type text}, {"Stock# Make (Short)", type text}, {"Stock# Make (Long)", type text}, {"Stock# Model (Short)", type text}, {"Stock# Model (Long)", type text}, {"Stock# Description", type text}, {"Stock# Serial Number", type text}, {"Document#", type text}, {"Document Last Print Counter", Int64.Type}, {"Document Code", type text}, {"Document Type (W/S/Q)", type text}, {"Document Status (O/R/C/k=Cancelled)", type text}, {"Document Posted? (P or ' ')", type text}, {"Document (Charge=R / Cash=S)", type text}, {"Document Credit Card", type text}, {"Document Credit Card Amount", type number}, {"Document Credit Card Expires (CCYYMM)", type text}, {"Document Credit Card Plan Number", type text}, {"Document Credit Card Tranx Date (CCYYMMDD)", type text}, {"Document Credit Card Tranx Date", type date}, {"Document Credit Card Tranx Time (HHMMSS)", type text}, {"Document Credit Card Tranx Auth#", type text}, {"Document Credit Card Tranx Auth. Status", type text}, {"Document Credit Card Tranx Settled (Y/N)", type text}, {"Document Credit Card Tranx Ref#", type text}, {"Date Opened (CCYYMMDD)", type text}, {"Date Opened", type date}, {"Days since Opened (Today-Opened)", Int64.Type}, {"Date Closed/Printed (CCYYMMDD)", type text}, {"Date Closed/Printed", type date}, {"Days to Close (Closed-Opened)", Int64.Type}, {"Days since Closed (Today-Closed)", Int64.Type}, {"Date Posted (CCYYMMDD)", type text}, {"Date Posted", type date}, {"Days to Post (Posted-Opened)", Int64.Type}, {"Days since Posted (Today-Posted)", Int64.Type}, {"Document Sold By Address#", type text}, {"Document Sold By Name", type text}, {"Document PO#", type text}, {"Document Amount (Parts)", type number}, {"Document Amount (Labor)", type number}, {"Document Amount (Other)", type number}, {"Document Amount (Total)", type number}, {"WIP Reason Open Code", type text}, {"WIP Reason Open Code Descr.", type text}, {"WIP Service Bay", type text}, {"WIP Labor Minimum Amount", type text}, {"WIP Labor Minimum Sales Code", type text}, {"WIP Labor Maximum Amount", type text}, {"WIP Labor Maximum Sales Code", type text}, {"WIP Non-Revenue? (Y=Yes)", type text}, {"WIP Last Note Date (CCYYMMDD)", type text}, {"WIP Last Note Date", type date}, {"WIP Last Note Time (HHMM)", type text}, {"WIP Last Note", type text}, {"WIP Followup Date (CCYYMMDD)", type text}, {"WIP Followup Date", type date}, {"WIP Start Date (CCYYMMDD)", type text}, {"WIP Start Date", type date}, {"WIP Est. Complete Date (CCYYMMDD)", type text}, {"WIP Est Complete Date", type date}, {"WIP Last Punch Date (CCYYMMDD)", type text}, {"WIP Last Punch Date", type date}, {"WIP Last Punch Days to Close (Closed - Last Punch)", Int64.Type}, {"WIP First Punch Days to Open (First Punch - Open Date)", Int64.Type}, {"Total Reported Hrs (HHMMSS)", type number}, {"Total Billed Hrs (HHMMSS)", type number}, {"Document Tax Number", type text}, {"Document GST Code", type text}, {"Overide Debit Acct (custom)", type text}, {"Document Transfer Out flag", type text}, {"Document Group/Van Code", type text}, {"Document Ship By", type text}, {"Document ShipTo: Name", type text}, {"Document ShipTo: Name (Ext)", type text}, {"Document ShipTo: Address", type text}, {"Document ShipTo: Address (Ext)", type text}, {"Document ShipTo: City, State", type text}, {"Document ShipTo: Zip Code", type text}, {"Document Rent Interval (I/M/W)", type text}, {"Document Rent Frequency", type text}, {"Document Rent Date (CCYYMMDD)", type text}, {"Document Rent Date", type date}, {"Work Order: ThermoKing SVC ", type text}, {"Work Order: ThermoKing Warr ", type text}, {"Work Order: Warranty Code", type text}, {"Work Order: Make (Short)", type text}, {"Work Order: Make (Long)", type text}, {"Work Order: Model (Short)", type text}, {"Work Order: Model (Long)", type text}, {"Work Order: Serial Number", type text}, {"Work Order: Hour Meter", type number}, {"Work Order: Unit Year (CCYY)", type text}, {"Work Order: Int. flag (A/S)", type text}, {"Work Order: Int. Addrs#/Stk#", type text}, {"Work Order: Int. Cust. Name", type text}, {"Work Order: Int. Stk# Make (Short)", type text}, {"Work Order: Int. Stk# Make (Long)", type text}, {"Work Order: Int. Stk# Model (Short)", type text}, {"Work Order: Int. Stk# Model (Long)", type text}, {"Work Order: Int. Stk# Descr.", type text}, {"Work Order: Int. Stk# Serial#", type text}, {"Work Order: Warr. Addrs#", type text}, {"Work Order: Warr. Name", type text}, {"Work Order: Customer Unit#", type text}, {"Work Order: Fleet Svc flag", type text}, {"Work Order: Flt Svc (CCYYMMDD)", type text}, {"Work Order: Flt Svc Date", type date}}),
    // Remove Duplicate columns from Customer tables, lots of redundant Mb's
    #"Remove Cust Columns" = Table.RemoveColumns(#"Change_Type",{"Customer Name", "Customer Name (Extended)", "Customer Street Address", "Customer Street Address (Extended)", "Customer City/State/Province", "Customer Postal Code", "Customer Phone-1 Area Code", "Customer Phone-2 PreFix", "Customer Phone-3 Base Number", "Customer Default EMAIL address", "Customer Default Tax Code (Standard: 1 character)", "Customer Default Tax Code (Advanced: 3 character)", "Customer Default Tax Type", "Customer Default Tax Number", "Customer Marketing Sort Code: 01", "Customer Marketing Sort Code: 02", "Customer Marketing Sort Code: 03", "Customer Marketing Sort Code: 04", "Customer Marketing Sort Code: 05", "Customer Marketing Sort Code: 06", "Customer Marketing Sort Code: 07", "Customer Marketing Sort Code: 08", "Customer Marketing Sort Code: 09", "Customer Marketing Sort Code: 10"}),
    // Comine Make/Model/Desc from Work Order/Work Order Int. / Stock#
    #"Add Model Combined" = Table.AddColumn(#"Remove Cust Columns", "Model Combined", each Text.Combine({
            [#"Work Order: Make (Short)"], [#"Work Order: Model (Short)"], [#"Work Order: Unit Year (CCYY)"], [#"Work Order: Serial Number"],
            [#"Work Order: Int. Stk# Make (Short)"], [#"Work Order: Int. Stk# Model (Short)"], [#"Work Order: Int. Stk# Descr."], [#"Work Order: Int. Stk# Serial#"],
            [#"Stock# Make (Short)"], [#"Stock# Model (Short)"], [#"Stock# Description"], [#"Stock# Serial Number"]
        }, " "), type text),
    // Ship to Name, City, State, Zip
    #"Add Ship To Name-Loc" = Table.AddColumn(#"Add Model Combined", "Ship To Name-Loc", each Text.Combine(
		{[#"Document ShipTo: Name"], [#"Document ShipTo: City, State"], [#"Document ShipTo: Zip Code"]},
		","), type text)


in
    #"Add Ship To Name-Loc"






/*
Orig before moving Key_Cust_Doc to Extract-Filter Step
let
    //Combine the statc history file and dynamic current file in to single data set to transform
    Source = POS_Summary_Extract_Filter,
    // Specify all column type, generated from data documentation workbook
    Change_Type = Table.TransformColumnTypes(#"Source",{{"Division", type text}, {"Addrs/Stk flag (A/S)", type text}, {"Address#/Stock#", type text}, {"Customer Name", type text}, {"Customer Name (Extended)", type text}, {"Customer Street Address", type text}, {"Customer Street Address (Extended)", type text}, {"Customer City/State/Province", type text}, {"Customer Postal Code", type text}, {"Customer Phone-1 Area Code", type text}, {"Customer Phone-2 PreFix", type text}, {"Customer Phone-3 Base Number", type text}, {"Customer Default EMAIL address", type text}, {"Customer Default Tax Code (Standard: 1 character)", type text}, {"Customer Default Tax Code (Advanced: 3 character)", type text}, {"Customer Default Tax Type", type text}, {"Customer Default Tax Number", type text}, {"Customer Marketing Sort Code: 01", type text}, {"Customer Marketing Sort Code: 02", type text}, {"Customer Marketing Sort Code: 03", type text}, {"Customer Marketing Sort Code: 04", type text}, {"Customer Marketing Sort Code: 05", type text}, {"Customer Marketing Sort Code: 06", type text}, {"Customer Marketing Sort Code: 07", type text}, {"Customer Marketing Sort Code: 08", type text}, {"Customer Marketing Sort Code: 09", type text}, {"Customer Marketing Sort Code: 10", type text}, {"Stock# Status", type text}, {"Stock# Make (Short)", type text}, {"Stock# Make (Long)", type text}, {"Stock# Model (Short)", type text}, {"Stock# Model (Long)", type text}, {"Stock# Description", type text}, {"Stock# Serial Number", type text}, {"Document#", type text}, {"Document Last Print Counter", Int64.Type}, {"Document Code", type text}, {"Document Type (W/S/Q)", type text}, {"Document Status (O/R/C/k=Cancelled)", type text}, {"Document Posted? (P or ' ')", type text}, {"Document (Charge=R / Cash=S)", type text}, {"Document Credit Card", type text}, {"Document Credit Card Amount", type number}, {"Document Credit Card Expires (CCYYMM)", type text}, {"Document Credit Card Plan Number", type text}, {"Document Credit Card Tranx Date (CCYYMMDD)", type text}, {"Document Credit Card Tranx Date", type date}, {"Document Credit Card Tranx Time (HHMMSS)", type text}, {"Document Credit Card Tranx Auth#", type text}, {"Document Credit Card Tranx Auth. Status", type text}, {"Document Credit Card Tranx Settled (Y/N)", type text}, {"Document Credit Card Tranx Ref#", type text}, {"Date Opened (CCYYMMDD)", type text}, {"Date Opened", type date}, {"Days since Opened (Today-Opened)", Int64.Type}, {"Date Closed/Printed (CCYYMMDD)", type text}, {"Date Closed/Printed", type date}, {"Days to Close (Closed-Opened)", Int64.Type}, {"Days since Closed (Today-Closed)", Int64.Type}, {"Date Posted (CCYYMMDD)", type text}, {"Date Posted", type date}, {"Days to Post (Posted-Opened)", Int64.Type}, {"Days since Posted (Today-Posted)", Int64.Type}, {"Document Sold By Address#", type text}, {"Document Sold By Name", type text}, {"Document PO#", type text}, {"Document Amount (Parts)", type number}, {"Document Amount (Labor)", type number}, {"Document Amount (Other)", type number}, {"Document Amount (Total)", type number}, {"WIP Reason Open Code", type text}, {"WIP Reason Open Code Descr.", type text}, {"WIP Service Bay", type text}, {"WIP Labor Minimum Amount", type text}, {"WIP Labor Minimum Sales Code", type text}, {"WIP Labor Maximum Amount", type text}, {"WIP Labor Maximum Sales Code", type text}, {"WIP Non-Revenue? (Y=Yes)", type text}, {"WIP Last Note Date (CCYYMMDD)", type text}, {"WIP Last Note Date", type date}, {"WIP Last Note Time (HHMM)", type text}, {"WIP Last Note", type text}, {"WIP Followup Date (CCYYMMDD)", type text}, {"WIP Followup Date", type date}, {"WIP Start Date (CCYYMMDD)", type text}, {"WIP Start Date", type date}, {"WIP Est. Complete Date (CCYYMMDD)", type text}, {"WIP Est Complete Date", type date}, {"WIP Last Punch Date (CCYYMMDD)", type text}, {"WIP Last Punch Date", type date}, {"WIP Last Punch Days to Close (Closed - Last Punch)", Int64.Type}, {"WIP First Punch Days to Open (First Punch - Open Date)", Int64.Type}, {"Total Reported Hrs (HHMMSS)", type number}, {"Total Billed Hrs (HHMMSS)", type number}, {"Document Tax Number", type text}, {"Document GST Code", type text}, {"Overide Debit Acct (custom)", type text}, {"Document Transfer Out flag", type text}, {"Document Group/Van Code", type text}, {"Document Ship By", type text}, {"Document ShipTo: Name", type text}, {"Document ShipTo: Name (Ext)", type text}, {"Document ShipTo: Address", type text}, {"Document ShipTo: Address (Ext)", type text}, {"Document ShipTo: City, State", type text}, {"Document ShipTo: Zip Code", type text}, {"Document Rent Interval (I/M/W)", type text}, {"Document Rent Frequency", type text}, {"Document Rent Date (CCYYMMDD)", type text}, {"Document Rent Date", type date}, {"Work Order: ThermoKing SVC ", type text}, {"Work Order: ThermoKing Warr ", type text}, {"Work Order: Warranty Code", type text}, {"Work Order: Make (Short)", type text}, {"Work Order: Make (Long)", type text}, {"Work Order: Model (Short)", type text}, {"Work Order: Model (Long)", type text}, {"Work Order: Serial Number", type text}, {"Work Order: Hour Meter", type number}, {"Work Order: Unit Year (CCYY)", type text}, {"Work Order: Int. flag (A/S)", type text}, {"Work Order: Int. Addrs#/Stk#", type text}, {"Work Order: Int. Cust. Name", type text}, {"Work Order: Int. Stk# Make (Short)", type text}, {"Work Order: Int. Stk# Make (Long)", type text}, {"Work Order: Int. Stk# Model (Short)", type text}, {"Work Order: Int. Stk# Model (Long)", type text}, {"Work Order: Int. Stk# Descr.", type text}, {"Work Order: Int. Stk# Serial#", type text}, {"Work Order: Warr. Addrs#", type text}, {"Work Order: Warr. Name", type text}, {"Work Order: Customer Unit#", type text}, {"Work Order: Fleet Svc flag", type text}, {"Work Order: Flt Svc (CCYYMMDD)", type text}, {"Work Order: Flt Svc Date", type date}}),
    // Remove Duplicate columns from Customer tables, lots of redundant Mb's
    #"Remove Cust Columns" = Table.RemoveColumns(#"Change_Type",{"Customer Name", "Customer Name (Extended)", "Customer Street Address", "Customer Street Address (Extended)", "Customer City/State/Province", "Customer Postal Code", "Customer Phone-1 Area Code", "Customer Phone-2 PreFix", "Customer Phone-3 Base Number", "Customer Default EMAIL address", "Customer Default Tax Code (Standard: 1 character)", "Customer Default Tax Code (Advanced: 3 character)", "Customer Default Tax Type", "Customer Default Tax Number", "Customer Marketing Sort Code: 01", "Customer Marketing Sort Code: 02", "Customer Marketing Sort Code: 03", "Customer Marketing Sort Code: 04", "Customer Marketing Sort Code: 05", "Customer Marketing Sort Code: 06", "Customer Marketing Sort Code: 07", "Customer Marketing Sort Code: 08", "Customer Marketing Sort Code: 09", "Customer Marketing Sort Code: 10"}),
    // Add a unique key to the table based on Customer and Document ID
    #"Add Key_Cust_Doc" = Table.AddColumn(#"Remove Cust Columns", "Key_Cust_Doc", 
        each Text.Combine({
            [#"Address#/Stock#"], [#"Document#"]
            },
            "-"),
        type text),
   //Promote new unique key
    #"Make Key_Cust_Doc Key" = Table.AddKey(
        #"Add Key_Cust_Doc",
        {"Key_Cust_Doc"},
        true),
    // Comine Make/Model/Desc from Work Order/Work Order Int. / Stock#
    #"Add Model Combined" = Table.AddColumn(#"Make Key_Cust_Doc Key", "Model Combined", each Text.Combine({
            [#"Work Order: Make (Short)"], [#"Work Order: Model (Short)"], [#"Work Order: Unit Year (CCYY)"], [#"Work Order: Serial Number"],
            [#"Work Order: Int. Stk# Make (Short)"], [#"Work Order: Int. Stk# Model (Short)"], [#"Work Order: Int. Stk# Descr."], [#"Work Order: Int. Stk# Serial#"],
            [#"Stock# Make (Short)"], [#"Stock# Model (Short)"], [#"Stock# Description"], [#"Stock# Serial Number"]
        }, " "), type text),
    // Ship to Name, City, State, Zip
    #"Add Ship To Name-Loc" = Table.AddColumn(#"Add Model Combined", "Ship To Name-Loc", each Text.Combine({[#"Document ShipTo: Name"], [#"Document ShipTo: City, State"], [#"Document ShipTo: Zip Code"]}, ","), type text)


in
    #"Add Ship To Name-Loc"
	*/