let
    Source = Units_Extract_Filter,
    #"Changed Type" = Table.TransformColumnTypes(Source,
    {{"Unit Number", type text}, {"Make (Short)", type text}, {"Make (Long)", type text}, {"Model (Short)", type text}, {"Model (Long)", type text}, {"Description", type text}, {"Serial Number", type text}, {"Engine Number", type text}, {"Status", type text}, {"Product Code", type text}, {"New/Used", type text}, {"Color Code", type text}, {"Horsepower", type text}, {"Hour Meter", type text}, {"Warranty Code on Unit", type text}, {"Location", type text}, {"Inventory Division", type text}, {"Inventory Account Number", type text}, {"Depreciation Method", type text}, {"Depreciation Life", Int64.Type}, {"Depreciation Expense Account", type text}, {"Depreciation Start Date (CCYYMMDD)", type text}, {"Depreciation Start Date", type date}, {"Depreciation Start Cost", type number}, {"Depreciation Salvage", type number}, {"Depreciation Past Years", type number}, {"Depreciation Current Year", type number}, {"Depreciation Life to Date", type number}, {"Depreciation Book Value (Cost - Depr)", type number}, {"Unit Suggested List Price", type number}, {"Unit Dealer List Price", type number}, {"Unit Cost (Total)", type number}, {"Unit Cost (Original)", type number}, {"Unit Cost (Added: Total-Orig)", type number}, {"Flooring Vendor#", type text}, {"Flooring Vendor Name", type text}, {"Flooring Account#", type text}, {"Flooring Account Title", type text}, {"Flooring Earliest Due Date (CCYYMMDD)", type text}, {"Flooring Earliest Due Date", type date}, {"Flooring Past Due", type number}, {"Flooring Due  1-30", type number}, {"Flooring Due 31-60", type number}, {"Flooring Due 61-90", type number}, {"Flooring Due 91-120", type number}, {"Flooring Due 121+", type number}, {"Flooring Total Due", type number}, {"Flooring Amount", type number}, {"Flooring Due Date (CCYYMMDD)", type text}, {"Flooring Due Date", type date}, {"Flooring Due Days (Flooring - Today)", Int64.Type}, {"Attachment Configured List Price", type number}, {"Attachment on Unit#", type text}, {"Primary Unit Configured List Price", type number}, {"Primary Unit (Y/N)", type text}, {"Unit Discount (%)", type number}, {"Start Rent Date (CCYYMMDD)", type text}, {"Start Rent Date", type date}, {"Start Rent Days (Today - Start Rent)", Int64.Type}, {"Rental Revenue", type number}, {"Rental Cost", type number}, {"Rental Status", type text}, {"Rental Status Date (CCYYMMDD)", type text}, {"Rental Status Date", type date}, {"Rental Status Days (Today - Status)", Int64.Type}, {"Rental Class", type text}, {"Rental Acquisition Cost", type number}, {"Rental Replacement Value", type number}, {"Fuel Type", type text}, {"Fuel Capacity", type number}, {"Rental Non-Serialized Quantity", type number}, {"Rental Damage Waiver (Y/N)", type text}, {"Rental Attachment Flag (Y/N)", type text}, {"Rental Customer Number", type text}, {"Rental Customer Name", type text}, {"Rental Contract Division", type text}, {"Rental Contract Number", type text}, {"Rental Date  On Rent (CCYYMMDD)", type text}, {"Rental Date  On Rent", type date}, {"Rental Date Off Rent (CCYYMMDD)", type text}, {"Rental Date Off Rent", type date}, {"Unit Year", type text}, {"Unit In Date (CCYYMMDD)", type text}, {"Unit In Date", type date}, {"Unit In Days (Today - In Date)", Int64.Type}, {"Sale Date (CCYYMMDD)", type text}, {"Sale Date", type date}, {"Sale Days (Sale Date - In Date)", Int64.Type}, {"Sold Days Past (Today - Sold Date)", Int64.Type}, {"Warranty Code (From Sales Tranx)", type text}, {"Warranty Expiration Date (CCYYMMDD)", type text}, {"Warranty Expiration Date", type date}, {"Warranty Expire Days (Expire - Today)", Int64.Type}, {"Invoice Number", type text}, {"Sale Account Number", type text}, {"Sale Amount", type number}, {"Sale Cost", type number}, {"Sale Profit (Amount - Cost)", type number}, {"Sold To Number", type text}, {"Sold To Name", type text}, {"Sold To Name (Extended)", type text}, {"Sold To Address", type text}, {"Sold To Address (Extended)", type text}, {"Sold To City/State", type text}, {"Sold To ZipCode", type text}, {"Sold To Phone Number", type text}, {"Sold To Default EMAIL address", type text}, {"Sort Codes", type text}, {"Sold By Number", type text}, {"Sold By Name", type text}, {"Customer (custom)", type text}, {"Trade On Unit#", type text}, {"Trade On Make (Short)", type text}, {"Trade On Make (Long)", type text}, {"Trade On Model (Short)", type text}, {"Trade On Model (Long)", type text}, {"Trade On Year", type text}, {"Trade On Description", type text}, {"Trade On Serial#", type text}, {"Trade On Sale Date (CCYYMMDD)", type text}, {"Trade On Sale Date", type date}, {"Trade On Invoice Number", type text}, {"Trade On Sale Amount", type number}, {"Trade On Cost", type number}, {"Trade On Profit (Amount - Cost)", type number}, {"Trade On Sold To Number", type text}, {"Trade On Sold To Name", type text}, {"Trade On Sold By Number", type text}, {"Trade On Sold By Name", type text}, {"Engine Make", type text}, {"Engine Model", type text}, {"Reserved Store", type text}, {"Reserved Employee", type text}, {"Reserved Date (CCYYMMDD)", type text}, {"Reserved Date", type date}}
    ),
    // Concatenate Unit Description in single field
    #"Add Unit Description" = Table.AddColumn(#"Changed Type", "Unit Description", each 
    Text.Combine({
        Text.Combine({[Unit Year], [#"Make (Short)"], [#"Model (Short)"], [Description]}, " "), 
        [Unit Long Description]}, "#lf"), 
    type text)
in
    #"Add Unit Description"