let
    Source = List.Dates(#"Start Date USE ME", DateRangeDays, #duration(1,0,0,0)),
    Today = DateTime.Date(DateTime.LocalNow()),
    #"Start Date Fixed" = #date(2015, 1, 1),
    #"End Date FIxed" = #date(2021, 12, 31),
    #"Start Current Year" = Date.StartOfYear(Today),
    #"Start Last Year" = Date.StartOfYear(Date.AddYears(Today, -1)),
    #"End Current Year" = Date.EndOfYear(Today),
    #"End Next Year" = Date.EndOfYear(Date.AddYears(Today, 1)),
    #"Start Date USE ME" = #"Start Date Fixed",
    #"End Date USE ME" = #"End Next Year",
    DateRangeDays = Duration.Days(#"End Date USE ME" - #"Start Date USE ME")+1,
    #"Converted to Table" = Table.FromList(#"Source", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    #"Inserted Date ISO" = Table.AddColumn(#"Changed Type", "Date ISO", each Date.ToText([Date], "yyyy-MM-dd"), type text),
    #"Inserted YYMM" = Table.AddColumn(#"Inserted Date ISO", "YYMM", each Date.ToText([Date], "yyMM"), Int64.Type),
    #"Inserted YYYY-MM" = Table.AddColumn(#"Inserted YYMM", "YYYY-MM", each Date.ToText([Date], "yyy-MM"), type text),
    #"Inserted MMM-YY" = Table.AddColumn(#"Inserted YYYY-MM", "MMM-YY", each Date.ToText([Date], "MMM-yy"), type text),
    #"Inserted Month Name" = Table.AddColumn(#"Inserted MMM-YY", "Month Name", each Date.MonthName([Date], "en-US"), type text),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Month Name", "Week of Month", each Date.WeekOfMonth([Date], Day.Sunday), Int64.Type),
    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Week of Month", "Day of Week", each Date.DayOfWeek([Date], Day.Sunday)+1, Int64.Type),
    #"Inserted Day of Week Name" = Table.AddColumn(#"Inserted Day of Week", "Day of Week Name", each Date.DayOfWeekName([Date], "en-US"), type text),
    #"Inserted Day" = Table.AddColumn(#"Inserted Day of Week Name", "Day", each Date.Day([Date]), Int64.Type),
    #"Inserted Calendar Year" = Table.AddColumn(#"Inserted Day", "Calenadar Year", each Date.Year([Date]), Int64.Type),
    #"Inserted Calendar Quarter" = Table.AddColumn(#"Inserted Calendar Year", "Calenadar Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Inserted Calendar Month" = Table.AddColumn(#"Inserted Calendar Quarter", "Calenadar Month", each Date.Month([Date]), Int64.Type),
    #"Inserted Calendar Week of Year" = Table.AddColumn(#"Inserted Calendar Month", "Calendar Week of Year", each Date.WeekOfYear([Date], Day.Sunday), Int64.Type),
    #"Inserted Calendar Day of Year" = Table.AddColumn(#"Inserted Calendar Week of Year", "Calendar Day of Year", each Date.DayOfYear([Date]), Int64.Type)
in
    #"Inserted Calendar Day of Year"