let
     Source = _Production_Data_Select,
    // Filter the files to include in the correct data source
    #"Filtered Files" = 
        Table.Buffer(
            Table.SelectRows(Source, each 
            Text.Contains(
                [Name], "Receivables_Master_Information") 
                // or Text.Contains([Name], "Detail_Posted") 
                // and Text.Contains([Name], "csv") // Need to ignore the "Detail_Posted*.xls until legacy workbooks retired and these files removed
                // and Number.FromText([year_posted]) >= date_year_posted_start // Dont want to touch these big old files if we dont need to
            )
        ),
    // Conditionally create table(and promote headers) from each file based upon file type
    #"Extract Table From File" = Table.AddColumn(#"Filtered Files", "Data", each 
        if Text.Contains([Extension], "xls") 
        then Table.PromoteHeaders(
                Excel.Workbook([Content]){[Item="Sheet1",Kind="Sheet"]}[Data]
            , [PromoteAllScalars=true])
        else if Text.Contains([Extension], "csv") 
        then Table.PromoteHeaders(
                Csv.Document([Content],[Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.None])
            , [PromoteAllScalars=true])
        else "Need to specify extraction method"),
    // expand the extracted table of each file into single table
    #"Expanded Data" = Table.ExpandTableColumn(#"Extract Table From File", 
        "Data", 
        // Column name to extract were hard coded, changed below to read columns from first table in file selections
        Table.ColumnNames(#"Extract Table From File"[#"Data"]{0})
        ),
    // Make the Customer# the key
    #"Make Customer# Key" = Table.AddKey(
        #"Expanded Data",
        {"Customer#"},
        true),
   
    //__________FILTERS____Filter Customer Table by Sales Data
   // create a list of customer# to fitler table by
   #"Create Filter List" = 
        if customer_include = "In Sales"
        then List.Buffer(List.Sort(List.Distinct(POS_Summary_Extract_Filter[#"Address#/Stock#"])))
        else if customer_include = "Custom"
        then {} //define a custom list here
        else {},
   //Apply filter using the filter list if customer_include parameter is not "All"
   #"Filter Customers" = 
        if customer_include = "All"
        then #"Make Customer# Key"
        else if customer_include = "None"
        then Table.FirstN(#"Make Customer# Key", 1)
        else Table.SelectRows(#"Make Customer# Key", each 
            List.Contains(
                #"Create Filter List",
                [#"Customer#"])),
    // #"Removed Columns" = Table.RemoveColumns(#"Filter Customers",{"Content", "Name", "Extension", "Date accessed", "Date modified", "Date created", "Attributes", "Folder Path", "year_posted"})
    // TODO Trying table.buffer on fitlered file?
    #"Removed Columns" = Table.RemoveColumns( 
        #"Filter Customers",
        Table.ColumnNames(#"Filtered Files")
        )
in
    #"Removed Columns"



     // move to transform
    // #"Change Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Deleted (*)", type text}, {"Division", type text}, {"Customer#", type text}, {"Allow New POS Documents (Y/N)", type text}, {"Use Instead Customer#", type text}, {"Use Instead Name", type text}, {"Sales Ranking Combined Customer#", type text}, {"Sales Ranking Combined Name", type text}, {"Sales Ranking Exclude (Y/N)", type text}, {"Customer Name", type text}, {"Customer Name (Extended)", type text}, {"Street Address", type text}, {"Street Address (Extended)", type text}, {"City  -  State/Province", type text}, {"Postal Code", type text}, {"Customer Tracked as Contact (Y/N)", type text}, {"Customer First Name (Contacts)", type text}, {"Customer Initial (Contacts)", type text}, {"Customer Last Name (Contacts)", type text}, {"Customer Company Name (Contacts)", type text}, {"Territory Code (Contacts)", type text}, {"Address - Line 1 (Contacts)", type text}, {"Address - Line 2 (Contacts)", type text}, {"Address - Line 3 (Contacts)", type text}, {"Address - City (Contacts)", type text}, {"Address - State/Prov (Contacts)", type text}, {"Customer Email (Contacts)", type text}, {"Customer Website (Contacts)", type text}, {"Day Area Code", type text}, {"Day Prefix", type text}, {"Day Number", type text}, {"Work Area Code", type text}, {"Work Prefix", type text}, {"Work Number", type text}, {"Work Extension", type text}, {"Fax Area Code", type text}, {"Fax Prefix", type text}, {"Fax Number", type text}, {"A/P Persons Phone#", type text}, {"A/P Persons Fax#", type text}, {"A/P Persons Name", type text}, {"A/P # with customer", type text}, {"Current # of Unpaid Invoices     (*NF*)", type text}, {"Balance    Total", type number}, {"Balance   Current", type number}, {"Balance  30 Day", type number}, {"Balance  60 Day", type number}, {"Balance  90 Day", type number}, {"Balance 120 Day", type number}, {"Balance Svc Chg", type number}, {"Balance at Peak", type number}, {"A/R GL Acct#", type text}, {"Date Added (CCYYMMDD)", type text}, {"Date Added", type date}, {"Date Added Days (Today - Added)", Int64.Type}, {"Open Item=O, Bal.Frwd=B", type text}, {"Credit Established (Y or N)", type text}, {"Credit Limit", type number}, {"Credit Code (1)", type text}, {"Credit Code (2)", type text}, {"Receivables Long Comment", type text}, {"Marketing Edit Code: 01 (W)", type text}, {"Marketing Edit Code: 02 (V)", type text}, {"Marketing Edit Code: 03 (E)", type text}, {"Marketing Edit Code: 04 (R)", type text}, {"Marketing Edit Code: 05 (M)", type text}, {"Marketing Edit Code: 06 (L)", type text}, {"Marketing Edit Code: 07 (C)", type text}, {"Marketing Edit Code: 08 (T)", type text}, {"Marketing Sort Code: 01", type text}, {"Marketing Sort Code: 02", type text}, {"Marketing Sort Code: 03", type text}, {"Marketing Sort Code: 04", type text}, {"Marketing Sort Code: 05", type text}, {"Marketing Sort Code: 06", type text}, {"Marketing Sort Code: 07", type text}, {"Marketing Sort Code: 08", type text}, {"Marketing Sort Code: 09", type text}, {"Marketing Sort Code: 10", type text}, {"Print Invoice (Y or N=Archive Only)", type text}, {"Print Statements (Y or N)", type text}, {"Email Invoices (Y or N)", type text}, {"Email Statements (Y or N)", type text}, {"Cash Only (Y/N)", type text}, {"Internal/Warranty (I/W)", type text}, {"Group Code", type text}, {"Discount Code", type text}, {"Quantity Discount (Y/N)", type text}, {"Tax Code (Standard: 1 character)", type text}, {"Tax Code (Advanced: 3 character)", type text}, {"Tax Type", type text}, {"Tax Number", type text}, {"GST Method (0/1/2/3)", type text}, {"GST Tax Number", type text}, {"SIC code", type text}, {"DUNS Number", type text}, {"DUNS Rating", type text}, {"FIPS code (State)", type text}, {"FIPS code (County)", type text}, {"Customer Rank", type text}, {"Freon Certification #", type text}, {"Rental Damage Waiver (Y/N)", type text}, {"Last Invoice Date (CCYYMMDD)", type text}, {"Last Invoice Date", type date}, {"Last Invoice Days (Today-Last Invoice)", Int64.Type}, {"Last Invoice Number", type text}, {"Last Invoice Amount", type number}, {"Last Payment Date (CCYYMMDD)", type text}, {"Last Payment Date", type date}, {"Last Payment Days (Today-Last Payment)", Int64.Type}, {"Last Payment Invoice #", type text}, {"Last Payment Amount", type number}, {"Annual Interest Rate", type number}, {"Basic Interest Charge", type number}, {"Charge Interest (Y/N)", type text}, {"Days till Interest", Int64.Type}, {"Days Collection Critical", Int64.Type}, {"Last Letter Date (CCYYMMDD)", type text}, {"Last Letter Date", type date}, {"Last Letter Days (Today-Lst Ltr)", Int64.Type}, {"Last Letter Number", type text}, {"Last Date Age Calc (CCYYMMDD)", type text}, {"Last Date Age Calculated", type date}, {"Last Date Age Calc Days(Today-Last Age)", Int64.Type}, {"Average # days Invoices Paid     (*NF*)", type number}, {"Roundup Interest Charge (Y/N)", type text}, {"Last Interest Date (CCYYMMDD)", type text}, {"Last Interest Date", type date}, {"Last Interest Days (Today-Last Interest)", Int64.Type}, {"Last Interest Invoice #", type text}, {"Last Interest Amount", type number}, {"Last Statement Date(CCYYMMDD)", type text}, {"Last Statement Date", type date}, {"Last Statement Days (Today-Last Stmnt)", Int64.Type}, {"Last Statement Balance", type number}})

    /* THESE were the hard coded column names in the expand
    {"Deleted (*)", "Division", "Customer#", "Allow New POS Documents (Y/N)", "Use Instead Customer#", "Use Instead Name", "Sales Ranking Combined Customer#", "Sales Ranking Combined Name", "Sales Ranking Exclude (Y/N)", "Customer Name", "Customer Name (Extended)", "Street Address", "Street Address (Extended)", "City  -  State/Province", "Postal Code", "Customer Tracked as Contact (Y/N)", "Customer First Name (Contacts)", "Customer Initial (Contacts)", "Customer Last Name (Contacts)", "Customer Company Name (Contacts)", "Territory Code (Contacts)", "Address - Line 1 (Contacts)", "Address - Line 2 (Contacts)", "Address - Line 3 (Contacts)", "Address - City (Contacts)", "Address - State/Prov (Contacts)", "Customer Email (Contacts)", "Customer Website (Contacts)", "Day Area Code", "Day Prefix", "Day Number", "Work Area Code", "Work Prefix", "Work Number", "Work Extension", "Fax Area Code", "Fax Prefix", "Fax Number", "A/P Persons Phone#", "A/P Persons Fax#", "A/P Persons Name", "A/P # with customer", "Current # of Unpaid Invoices     (*NF*)", "Balance    Total", "Balance   Current", "Balance  30 Day", "Balance  60 Day", "Balance  90 Day", "Balance 120 Day", "Balance Svc Chg", "Balance at Peak", "A/R GL Acct#", "Date Added (CCYYMMDD)", "Date Added", "Date Added Days (Today - Added)", "Open Item=O, Bal.Frwd=B", "Credit Established (Y or N)", "Credit Limit", "Credit Code (1)", "Credit Code (2)", "Receivables Long Comment", "Marketing Edit Code: 01 (W)", "Marketing Edit Code: 02 (V)", "Marketing Edit Code: 03 (E)", "Marketing Edit Code: 04 (R)", "Marketing Edit Code: 05 (M)", "Marketing Edit Code: 06 (L)", "Marketing Edit Code: 07 (C)", "Marketing Edit Code: 08 (T)", "Marketing Sort Code: 01", "Marketing Sort Code: 02", "Marketing Sort Code: 03", "Marketing Sort Code: 04", "Marketing Sort Code: 05", "Marketing Sort Code: 06", "Marketing Sort Code: 07", "Marketing Sort Code: 08", "Marketing Sort Code: 09", "Marketing Sort Code: 10", "Print Invoice (Y or N=Archive Only)", "Print Statements (Y or N)", "Email Invoices (Y or N)", "Email Statements (Y or N)", "Cash Only (Y/N)", "Internal/Warranty (I/W)", "Group Code", "Discount Code", "Quantity Discount (Y/N)", "Tax Code (Standard: 1 character)", "Tax Code (Advanced: 3 character)", "Tax Type", "Tax Number", "GST Method (0/1/2/3)", "GST Tax Number", "SIC code", "DUNS Number", "DUNS Rating", "FIPS code (State)", "FIPS code (County)", "Customer Rank", "Freon Certification #", "Rental Damage Waiver (Y/N)", "Last Invoice Date (CCYYMMDD)", "Last Invoice Date", "Last Invoice Days (Today-Last Invoice)", "Last Invoice Number", "Last Invoice Amount", "Last Payment Date (CCYYMMDD)", "Last Payment Date", "Last Payment Days (Today-Last Payment)", "Last Payment Invoice #", "Last Payment Amount", "Annual Interest Rate", "Basic Interest Charge", "Charge Interest (Y/N)", "Days till Interest", "Days Collection Critical", "Last Letter Date (CCYYMMDD)", "Last Letter Date", "Last Letter Days (Today-Lst Ltr)", "Last Letter Number", "Last Date Age Calc (CCYYMMDD)", "Last Date Age Calculated", "Last Date Age Calc Days(Today-Last Age)", "Average # days Invoices Paid     (*NF*)", "Roundup Interest Charge (Y/N)", "Last Interest Date (CCYYMMDD)", "Last Interest Date", "Last Interest Days (Today-Last Interest)", "Last Interest Invoice #", "Last Interest Amount", "Last Statement Date(CCYYMMDD)", "Last Statement Date", "Last Statement Days (Today-Last Stmnt)", "Last Statement Balance", "Salesperson Addrs#", "Salesperson Name", "Sales Rep Addrs# (Contacts)", "Sales Rep First Name (Contacts)", "Sales Rep Last Name (Contacts)", "Corporate Address #", "Corporate Name", "Insurance Agency Name", "Insurance Agency Phone#", "Insurance Name of Agent", "Insurance Policy Number", "Insurance Policy Expire Date(CCYYMMDD)", "Insurance Policy Expire Date", "Insurance Policy Expires (Days left)"}, {"Deleted (*)", "Division", "Customer#", "Allow New POS Documents (Y/N)", "Use Instead Customer#", "Use Instead Name", "Sales Ranking Combined Customer#", "Sales Ranking Combined Name", "Sales Ranking Exclude (Y/N)", "Customer Name", "Customer Name (Extended)", "Street Address", "Street Address (Extended)", "City  -  State/Province", "Postal Code", "Customer Tracked as Contact (Y/N)", "Customer First Name (Contacts)", "Customer Initial (Contacts)", "Customer Last Name (Contacts)", "Customer Company Name (Contacts)", "Territory Code (Contacts)", "Address - Line 1 (Contacts)", "Address - Line 2 (Contacts)", "Address - Line 3 (Contacts)", "Address - City (Contacts)", "Address - State/Prov (Contacts)", "Customer Email (Contacts)", "Customer Website (Contacts)", "Day Area Code", "Day Prefix", "Day Number", "Work Area Code", "Work Prefix", "Work Number", "Work Extension", "Fax Area Code", "Fax Prefix", "Fax Number", "A/P Persons Phone#", "A/P Persons Fax#", "A/P Persons Name", "A/P # with customer", "Current # of Unpaid Invoices     (*NF*)", "Balance    Total", "Balance   Current", "Balance  30 Day", "Balance  60 Day", "Balance  90 Day", "Balance 120 Day", "Balance Svc Chg", "Balance at Peak", "A/R GL Acct#", "Date Added (CCYYMMDD)", "Date Added", "Date Added Days (Today - Added)", "Open Item=O, Bal.Frwd=B", "Credit Established (Y or N)", "Credit Limit", "Credit Code (1)", "Credit Code (2)", "Receivables Long Comment", "Marketing Edit Code: 01 (W)", "Marketing Edit Code: 02 (V)", "Marketing Edit Code: 03 (E)", "Marketing Edit Code: 04 (R)", "Marketing Edit Code: 05 (M)", "Marketing Edit Code: 06 (L)", "Marketing Edit Code: 07 (C)", "Marketing Edit Code: 08 (T)", "Marketing Sort Code: 01", "Marketing Sort Code: 02", "Marketing Sort Code: 03", "Marketing Sort Code: 04", "Marketing Sort Code: 05", "Marketing Sort Code: 06", "Marketing Sort Code: 07", "Marketing Sort Code: 08", "Marketing Sort Code: 09", "Marketing Sort Code: 10", "Print Invoice (Y or N=Archive Only)", "Print Statements (Y or N)", "Email Invoices (Y or N)", "Email Statements (Y or N)", "Cash Only (Y/N)", "Internal/Warranty (I/W)", "Group Code", "Discount Code", "Quantity Discount (Y/N)", "Tax Code (Standard: 1 character)", "Tax Code (Advanced: 3 character)", "Tax Type", "Tax Number", "GST Method (0/1/2/3)", "GST Tax Number", "SIC code", "DUNS Number", "DUNS Rating", "FIPS code (State)", "FIPS code (County)", "Customer Rank", "Freon Certification #", "Rental Damage Waiver (Y/N)", "Last Invoice Date (CCYYMMDD)", "Last Invoice Date", "Last Invoice Days (Today-Last Invoice)", "Last Invoice Number", "Last Invoice Amount", "Last Payment Date (CCYYMMDD)", "Last Payment Date", "Last Payment Days (Today-Last Payment)", "Last Payment Invoice #", "Last Payment Amount", "Annual Interest Rate", "Basic Interest Charge", "Charge Interest (Y/N)", "Days till Interest", "Days Collection Critical", "Last Letter Date (CCYYMMDD)", "Last Letter Date", "Last Letter Days (Today-Lst Ltr)", "Last Letter Number", "Last Date Age Calc (CCYYMMDD)", "Last Date Age Calculated", "Last Date Age Calc Days(Today-Last Age)", "Average # days Invoices Paid     (*NF*)", "Roundup Interest Charge (Y/N)", "Last Interest Date (CCYYMMDD)", "Last Interest Date", "Last Interest Days (Today-Last Interest)", "Last Interest Invoice #", "Last Interest Amount", "Last Statement Date(CCYYMMDD)", "Last Statement Date", "Last Statement Days (Today-Last Stmnt)", "Last Statement Balance", "Salesperson Addrs#", "Salesperson Name", "Sales Rep Addrs# (Contacts)", "Sales Rep First Name (Contacts)", "Sales Rep Last Name (Contacts)", "Corporate Address #", "Corporate Name", "Insurance Agency Name", "Insurance Agency Phone#", "Insurance Name of Agent", "Insurance Policy Number", "Insurance Policy Expire Date(CCYYMMDD)", "Insurance Policy Expire Date", "Insurance Policy Expires (Days left)"}
    */